{% set version = "0.3.63" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hiver
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HiveR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HiveR/HiveR_{{ version }}.tar.gz
  sha256: 83c16ab55324f51ac3f5d0377244fddcb7a009ae30cee4dd67270035c42422ee

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-rcolorbrewer
    - r-jpeg
    - r-plyr
    - r-png
    - r-rgl
    - r-tkrgl
  run:
    - r-base
    - r-rcolorbrewer
    - r-jpeg
    - r-plyr
    - r-png
    - r-rgl
    - r-tkrgl

test:
  commands:
    - $R -e "library('HiveR')"           # [not win]
    - "\"%R%\" -e \"library('HiveR')\""  # [win]

about:
  home: https://github.com/bryanhanson/HiveR
  license: GPL-3.0-only
  summary: 'Creates and plots 2D and 3D hive plots. Hive plots are a unique method of displaying networks of many types in which node properties are mapped to axes using meaningful properties rather than being arbitrarily positioned.  The hive plot concept was invented by Martin Krzywinski at the Genome Science Center (www.hiveplot.net/).  Keywords:
    networks, food webs, linnet, systems biology, bioinformatics.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: HiveR
# Type: Package
# Title: 2D and 3D Hive Plots for R
# Version: 0.3.42
# Date: 2017-07-27
# Authors@R: c(person(given = "Bryan A.", family = "Hanson", role = c("aut", "cre"), email = "hanson@depauw.edu"), person("Vesna", "Memisevic", role = "ctb"), person("Jonathan", "Chung", role = "ctb"))
# Description: Creates and plots 2D and 3D hive plots. Hive plots are a unique method of displaying networks of many types in which node properties are mapped to axes using meaningful properties rather than being arbitrarily positioned.  The hive plot concept was invented by Martin Krzywinski at the Genome Science Center (www.hiveplot.net/).  Keywords: networks, food webs, linnet, systems biology, bioinformatics.
# License: GPL-3
# Imports: grid, plyr, jpeg, png, RColorBrewer, utils, stats, rgl, tkrgl, tcltk
# Suggests: FuncMap, knitr, sna, xtable, bipartite
# URL: https://github.com/bryanhanson/HiveR
# ByteCompile: TRUE
# BugReports: https://github.com/bryanhanson/HiveR/issues
# VignetteBuilder: knitr
# Depends: R (>= 3.0)
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-07-27 23:19:38 UTC; bryanhanson
# Author: Bryan A. Hanson [aut, cre], Vesna Memisevic [ctb], Jonathan Chung [ctb]
# Maintainer: Bryan A. Hanson <hanson@depauw.edu>
# Repository: CRAN
# Date/Publication: 2017-07-28 08:55:02 UTC
