appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: fpwGaS5+1Z773VmXN0crHURbExVJlg1FSiAwsWVsj8KZdxkfIYPegI354xjhg8DGnMffNR4x3uxCSYsh4TlrAO3jLkR8HuLfR7n4nG/X1PBi5yEZHkhDi+pEGN19BJplIzXXMoCoAPlPOot7nAyxR2QuQ8nM+tyudssh4oy24+Ej9IzL1leauW2/auJXWN1oQeGs9s/CMArjJ1vooMY53Wey8+UoSnvdAiJ2NDmbtepd0x/y4DnPVc8EuPkA0+Xnnp8FbEaDG1scxm6YcRe+SRB+BY25+5D3y5kLJWGs7lciAU5vdXzCQC3J1+f5uIw5HH0pdHf8Cwq77Y7AIuf6wZqzrJ9fdVfDiC0DcNhCPXgiS8jKy3SR2ZuCBqqEW/Hubq+FawrNS0BsTwxmr96o6ko/MqgMe26PBBaRHqr+XQiW+p0XuowoCxfawJvtm2WOod6W0usKAj+2wyRVs/SvhHOmfn53mo8eeaXbGA+/5+pywYrUzLPkaRb2TMT9bLtQRZljwT0RLJadPpGH4gmL9u86K+vYthyS3j0iM5zAbA8wFkHPveVeIvhhU+Z3NQWVppgAOco6amkN8rhl/gEx4h9JRtCTN5nAfFLr4jAkm8yNsE7r3eriJs07HyC+1Dig8L27IyN1zd8LkmdVGD1R7kZpm6OWCabu5wTfyyULaKU=}
bot:
  automerge: true
